#!/bin/bash

#
# Copyright (c) 2016 Lars Boegild Thomsen <lth@cow.dk>
#

[ -z "$USER" ] && USER=lbthomsen

[ -d "prime" ] || mkdir prime

# Don't overwrite prime.txt file if it already exists!
[ -f "prime/prime.txt" ] || { cat <<-EOF > prime/prime.txt
V24OptionsConverted=1
WGUID_version=2
StressTester=0
UsePrimenet=1
DialUp=0
V5UserID=$USER
AskedAboutMemory=1
WorkPreference=0

[PrimeNet]
Debug=0
ProxyHost=
EOF
}

# Don't overwrite local.txt file if it already exists!
[ -f "prime/local.txt" ] || { cat <<-EOF > prime/local.txt
ComputerID=$HOSTNAME
EOF
}

mprime -wprime

