#!/bin/bash

#
# Copyright (c) 2015 Lars Boegild Thomsen <lth@cow.dk>
#

[ -z "$USER" ] && USER=lbthomsen

[ -d "prime" ] || mkdir prime

cat <<-EOF > prime/prime.txt
V24OptionsConverted=1
WGUID_version=2
StressTester=0
UsePrimenet=1
DialUp=0
V5UserID=$USER
AskedAboutMemory=1
WorkPreference=0

[PrimeNet]
Debug=0
ProxyHost=
EOF

cat <<-EOF > prime/local.txt
ComputerID=$HOSTNAME
EOF

mprime -wprime

