#!/bin/bash

#
# Written by Lars Boegild Thomsen <lth@cow.dk>
#

[ -z "$USER" ] && USER=lbthomsen

[ -d "prime" ] || mkdir prime

# Don't overwrite prime.txt file if it already exists!
[ -f "prime/prime.txt" ] || { cat <<-EOF > prime/prime.txt
V24OptionsConverted=1
WGUID_version=2
StressTester=0
UsePrimenet=1
DialUp=0
V5UserID=$USER
DiskWriteTime=15
NetworkRetryTime=5
NetworkRetryTime2=25
DaysOfWork=2
DaysBetweenCheckins=          1

[PrimeNet]
Debug=0
ProxyHost=

[Worker #1]
WorkPreference=0
EOF
}

# Don't overwrite local.txt file if it already exists!
[ -f "prime/local.txt" ] || { cat <<-EOF > prime/local.txt
ComputerID=$HOSTNAME
EOF
}

mprime -wprime

